name: CMake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Check Eigen installation
      id: check-eigen
      run: |
        cmake --version
        pkg-config --exists eigen3
        echo "::set-output name=found::$?"

    
    - name: Build and Execute
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./myProject
