name: CMake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Check Eigen installation
      id: check-eigen
      run: |
        cmake --version
        echo "::set-output name=found::$(cmake -E chdir build cmake --find-package -DNAME=Eigen3)"      
    
    - name: Build and Execute
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./myProject
